### ISSUE TITLE
Relation to Table does not exist

### ISSUE THREAD

**Issue by imFarrukh** [NYCPlanning/labs-postgis-preview#55]
I am typing my query in query tab as 
Select * from Fuel (My Table/layer present in the postgis Database)
**But em getting message realtion "Fuel" Does not exist.**  Same result for other tables.
When i am using this query in pgadmin there is no issue. 
Can anyone guide me what to do.
Any suggestion 
![image](https://user-images.githubusercontent.com/23632157/32599286-e92c0704-c55d-11e7-868c-50d9ff83c5c3.png)

**Comment by rajanski** [comment]
If the table in question is not in schema public, maybe try to set search_path to include the other schema too or alternatively query the table as in " select * from "my_other_schema"."Fuel" . Or check uppercase / lowercase issues with the table name

**Comment by imFarrukh** [comment]
![image](https://user-images.githubusercontent.com/23632157/32599925-c6630518-c55f-11e7-899f-1517c10f10cf.png)
My table is in "Schemas-Public"

**Comment by imFarrukh** [comment]
Thank you Rajanski ,,,,i fixed my issue just placing " " this :) Thanks for your guidance

**Comment by chriswhong** [comment]
Closing as this seems to have been resolved

**Comment by erickndava** [comment]
I am having this issue. Have tried the "area_bounds"."wards" (in my case) still getting relation does not exist. Any pointers?

**Comment by chriswhong** [comment]
Can you post a screenshot of the working query in another tool like pgAdmin?  Just want to make sure the table names are correct.

**Comment by imFarrukh** [comment]
> Can you post a screenshot of the working query in another tool like pgAdmin? Just want to make sure the table names are correct.

Chris Thank you ......,i fixed my issue just placing " " this :) Thanks u once again :)

**Comment by erickndava** [comment]
> Can you post a screenshot of the working query in another tool like pgAdmin? Just want to make sure the table names are correct.

Query in DBeaver

![dbeaver](https://user-images.githubusercontent.com/5484204/55011546-b17bc480-4fee-11e9-9470-a4b5acf22c7c.PNG)

Same query in Postgis-Preview.

![postgis-preview](https://user-images.githubusercontent.com/5484204/55011722-fdc70480-4fee-11e9-8d59-52c81635020e.PNG)

**Comment by chriswhong** [comment]
Assume you have tried just saying `public.wards` without the quotes?

**Comment by erickndava** [comment]
Yes. That was the first shot. The quotes came after reading the thread and
attempting to 'make it work'.

**Comment by erickndava** [comment]
Here's the data (csv) exported from the public schema.

[wards_201904032252.zip](https://github.com/NYCPlanning/labs-postgis-preview/files/3040721/wards_201904032252.zip)
